/**
BUSINESS REQUIREMENTS:

PERFORM SCD TYPE 2 TO MAINTAIN HISTORICAL DATA BY CREATING NEW RECORDS FOR EACH CHANGE, ENSURING THAT NO HISTORICAL DATA IS LOST.

NOTE: USE THE MERGE OPERATION

**/

Select *
From EMADE_OFFICE_ITEMS

--NEW RUN ALTER TARGET AND ADD IS_ACTIVE COLUMN
ALTER TABLE EMADE_OFFICE_ITEMS ADD IS_ACTIVE VARCHAR(50)
--SCD TYPE 2 IMPLEMENTATION 
INSERT INTO EMADE_OFFICE_ITEMS (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_OFFICE_ITEMS AS TARGET
    USING STG_EMADE_OFFICE_ITEMS AS SOURCE
    -- Join on ID and ensure we are looking at the CURRENT active record in Target
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND SOURCE.IS_ACTIVE = 'Y'
    
    -- ONLY MATCH IF DATA HAS ACTUALLY CHANGED
    WHEN MATCHED AND (TARGET.PRICE <> SOURCE.PRICE OR TARGET.PRODUCTNAME <> SOURCE.PRODUCTNAME) THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N'  -- Close the old history
    
    -- INSERT IF PRODUCT IS BRAND NEW
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, SOURCE.IS_ACTIVE)
    
    -- CAPTURE THE ACTION AND THE NEW SOURCE DATA
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        SOURCE.IS_ACTIVE
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
WHERE ACTION = 'UPDATE'; -- Only insert new row if we closed an old row (meaning a change occurred)
GO

--OLD SCD TYPE PROJECT 1: OFFICE_ITEMS
DROP TABLE IF EXISTS EMADE_OFFICE_ITEMS
CREATE TABLE EMADE_OFFICE_ITEMS(
    PRODUCTID		INT,
    PRODUCTNAME		VARCHAR(50),
    PRICE			DECIMAL(9,2)
)
GO
    
INSERT INTO EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE) VALUES(1,'TABLE',100)
INSERT INTO EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE) VALUES(2,'DESK',180)
INSERT INTO EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE) VALUES(3,'CHAIR',50)
INSERT INTO EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE) VALUES(4,'COMPUTER',300)
GO

DROP TABLE IF EXISTS STG_EMADE_OFFICE_ITEMS    
CREATE TABLE STG_EMADE_OFFICE_ITEMS(
    PRODUCTID		INT,
    PRODUCTNAME		VARCHAR(50),
    PRICE			DECIMAL(9,2),
	IS_ACTIVE		VARCHAR(50)
)
GO
    
INSERT INTO STG_EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE, IS_ACTIVE) VALUES(1,'TABLE',100,'Y')
INSERT INTO STG_EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE, IS_ACTIVE) VALUES(2,'DESK',80,'Y')
INSERT INTO STG_EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE, IS_ACTIVE) VALUES(5,'BED',50, 'Y')
INSERT INTO STG_EMADE_OFFICE_ITEMS(PRODUCTID,PRODUCTNAME, PRICE, IS_ACTIVE) VALUES(6,'CUPBOARD',300, 'Y')
GO


--CHECK TABLES  
SELECT * FROM EMADE_OFFICE_ITEMS    
SELECT * FROM STG_EMADE_OFFICE_ITEMS

--RUN ALTER TARGET AND ADD IS_ACTIVE COLUMN
ALTER TABLE EMADE_OFFICE_ITEMS ADD IS_ACTIVE VARCHAR(50)
--SCD TYPE 2 IMPLEMENTATION 
INSERT INTO EMADE_OFFICE_ITEMS (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_OFFICE_ITEMS AS TARGET
    USING STG_EMADE_OFFICE_ITEMS AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND SOURCE.IS_ACTIVE = 'Y'
    WHEN MATCHED THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N'
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, SOURCE.IS_ACTIVE)
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        SOURCE.IS_ACTIVE
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';







--SCD TYPE -- PROJECT 2: EMADE_SNACKS
-- DROP TABLES IF THEY EXIST
DROP TABLE IF EXISTS EMADE_SNACKS;

-- CREATE TARGET TABLE
CREATE TABLE EMADE_SNACKS (
    PRODUCTID INT NOT NULL,
    PRODUCTNAME VARCHAR(50),
    PRICE MONEY,
    STARTDATE DATE,
    ENDDATE DATE,
    IS_ACTIVE VARCHAR(1)
);

-- INSERT INITIAL DATA INTO TARGET TABLE
INSERT INTO EMADE_SNACKS (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
VALUES
    (101, 'TEA', 10.00, '2024-01-01', NULL, 'Y'),
    (102, 'COFFEE', 15.00, '2024-01-01', NULL, 'Y'),
    (103, 'BISCUITS', 20.00, '2024-01-01', NULL, 'Y');


DROP TABLE IF EXISTS STG_EMADE_SNACKS;
-- CREATE SOURCE TABLE
CREATE TABLE STG_EMADE_SNACKS (
    PRODUCTID INT NOT NULL,
    PRODUCTNAME VARCHAR(50),
    PRICE MONEY
);

-- INSERT UPDATED DATA INTO SOURCE TABLE
INSERT INTO STG_EMADE_SNACKS (PRODUCTID, PRODUCTNAME, PRICE)
VALUES
    (101, 'TEA', 10.00),
    (102, 'COFFEE', 35.00),
    (104, 'CHIPS', 22.00);

--CHECK TABLES  
SELECT * FROM EMADE_SNACKS    
SELECT * FROM STG_EMADE_SNACKS

INSERT INTO EMADE_SNACKS (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_SNACKS AS TARGET
    USING STG_EMADE_SNACKS AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND TARGET.IS_ACTIVE = 'Y'
    
    -- ONLY MATCH IF DATA HAS ACTUALLY CHANGED
    WHEN MATCHED AND (TARGET.PRICE <> SOURCE.PRICE OR TARGET.PRODUCTNAME <> SOURCE.PRODUCTNAME) THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N',
            TARGET.ENDDATE = DATEADD(day, -1, CAST(GETDATE() AS DATE)) -- Close history yesterday
    
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, CAST(GETDATE() AS DATE), NULL, 'Y')
    
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        CAST(GETDATE() AS DATE), -- New Start Date
        NULL,                    -- New End Date (Open)
        'Y'                      -- New Is Active
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';
GO


--SCD TYPE 2 IMPLEMENTATION 
INSERT INTO EMADE_SNACKS (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_SNACKS AS TARGET
    USING STG_EMADE_SNACKS AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND TARGET.IS_ACTIVE = 'Y'
    WHEN MATCHED THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N',
           -- TARGET.END_DATE = GETDATE() OR USE SYSTEM TIME WITH CAST(GETDATE() AS DATE)
		    TARGET.ENDDATE = DATEADD(day,-1,CAST(GETDATE() AS DATE))
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, CAST(GETDATE() AS DATE), NULL, 'Y')
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        CAST(GETDATE() AS DATE),
        NULL,
        'Y'
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';
